# -*- coding: utf-8 -*-
"""Licence gate for fake-trial-poke.

Generated by ``keyguard scaffold-app``.  General policy lives in
``keyguard.appgate.AppGate``; this module only binds application-specific
names.  Call ``enforce_or_exit()`` before opening ports or spawning workers.

The local fallback is intentionally tiny.  It only handles a build that lost
the entire keyguard package, which must fail open at customer runtime and fail
the mandatory package check at build time.
"""
from __future__ import annotations

import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

APP_ID = "FAKE_TRIAL_POKE"
APP_NAME = "fake-trial-poke"
ENFORCE_ENV = "FAKE_TRIAL_POKE_LICENCE_ENFORCE"
EMAIL_ENV = "FAKE_TRIAL_POKE_LICENCE_EMAIL"

try:
    from keyguard.appgate import AppGate, LicenceState, console_safe
except ImportError:
    @dataclass
    class LicenceState:
        allowed: bool
        status: str
        message: str
        days_remaining: Optional[int] = None
        enforced: bool = False
        email: str = ""

        @property
        def should_warn(self) -> bool:
            return (
                self.allowed
                and self.days_remaining is not None
                and self.days_remaining <= 14
            )

        def to_dict(self) -> dict:
            return {
                "allowed": self.allowed,
                "status": self.status,
                "message": self.message,
                "days_remaining": self.days_remaining,
                "enforced": self.enforced,
                "email": self.email,
                "should_warn": self.should_warn,
            }

    def console_safe(text: str) -> str:
        for bad, good in (("—", "-"), ("–", "-"), ("→", "->"), ("…", "...")):
            text = text.replace(bad, good)
        return text

    class _MissingGate:
        app_id = APP_ID
        app_name = APP_NAME
        enforce_env = ENFORCE_ENV
        email_env = EMAIL_ENV

        @staticmethod
        def state_dir() -> Path:
            return Path(os.environ.get("APPDATA") or Path.home()) / APP_NAME

        @classmethod
        def config_path(cls) -> Path:
            return cls.state_dir() / "licence.json"

        @staticmethod
        def should_enforce() -> bool:
            value = os.environ.get(ENFORCE_ENV, "").strip().lower()
            if value in ("1", "true", "yes", "on"):
                return True
            if value in ("0", "false", "no", "off"):
                return False
            return bool(getattr(sys, "frozen", False))

        @classmethod
        def licensee_email(cls) -> str:
            return os.environ.get(EMAIL_ENV, "").strip()

        @staticmethod
        def set_licensee_email(email: str) -> None:
            os.environ[EMAIL_ENV] = email.strip()

        @classmethod
        def check(cls) -> LicenceState:
            return LicenceState(
                True,
                "unknown",
                "keyguard not installed",
                enforced=cls.should_enforce(),
                email=cls.licensee_email(),
            )

        @staticmethod
        def activate(key: str, email: str = "") -> tuple[bool, str]:
            return False, "keyguard is not installed in this build"

        @staticmethod
        def machine_id() -> str:
            return ""

        @classmethod
        def enforce_or_exit(cls) -> LicenceState:
            return cls.check()

    GATE = _MissingGate()
else:
    GATE = AppGate(
        APP_ID,
        app_name=APP_NAME,
        enforce_env=ENFORCE_ENV,
        email_env=EMAIL_ENV,
    )

# Stable application-facing surface.
check = GATE.check
activate = GATE.activate
machine_id = GATE.machine_id
licensee_email = GATE.licensee_email
set_licensee_email = GATE.set_licensee_email
should_enforce = GATE.should_enforce
enforce_or_exit = GATE.enforce_or_exit

# Compatibility helpers used by existing integrations and their tests.
_user_data_dir = GATE.state_dir
_config_path = GATE.config_path
_console_safe = console_safe
