# -*- coding: utf-8 -*-
"""Licence gate for fake-trial-poke.

Generated by ``keyguard scaffold-app``.  General policy lives in
``keyguard.appgate.AppGate``; this module only binds application-specific
names.  Call ``enforce_or_exit()`` before opening ports or spawning workers.

The local fallback is intentionally tiny.  It only handles a build that lost
the entire keyguard package, which must fail open at customer runtime and fail
the mandatory package check at build time.
"""
from __future__ import annotations

import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

APP_ID = "FAKE_TRIAL_POKE"
APP_NAME = "fake-trial-poke"
ENFORCE_ENV = "FAKE_TRIAL_POKE_LICENCE_ENFORCE"
EMAIL_ENV = "FAKE_TRIAL_POKE_LICENCE_EMAIL"

try:
    from keyguard.appgate import AppGate, LicenceState, console_safe
except ImportError:
    @dataclass
    class LicenceState:
        allowed: bool
        status: str
        message: str
        days_remaining: Optional[int] = None
        enforced: bool = False
        email: str = ""

        @property
        def should_warn(self) -> bool:
            return (
                self.allowed
                and self.days_remaining is not None
                and self.days_remaining <= 14
            )

        def to_dict(self) -> dict:
            return {
                "allowed": self.allowed,
                "status": self.status,
                "message": self.message,
                "days_remaining": self.days_remaining,
                "enforced": self.enforced,
                "email": self.email,
                "should_warn": self.should_warn,
            }

    def console_safe(text: str) -> str:
        for bad, good in (("—", "-"), ("–", "-"), ("→", "->"), ("…", "...")):
            text = text.replace(bad, good)
        return text

    class _MissingGate:
        app_id = APP_ID
        app_name = APP_NAME
        enforce_env = ENFORCE_ENV
        email_env = EMAIL_ENV

        @staticmethod
        def state_dir() -> Path:
            return Path(os.environ.get("APPDATA") or Path.home()) / APP_NAME

        @classmethod
        def config_path(cls) -> Path:
            return cls.state_dir() / "licence.json"

        @staticmethod
        def should_enforce() -> bool:
            value = os.environ.get(ENFORCE_ENV, "").strip().lower()
            if value in ("1", "true", "yes", "on"):
                return True
            if value in ("0", "false", "no", "off"):
                return False
            return bool(getattr(sys, "frozen", False))

        @classmethod
        def licensee_email(cls) -> str:
            # Env var first, then licence.json -- the same order AppGate uses.
            # Reading only the env var made a configured address invisible here,
            # so the same command printed different licensees depending on
            # whether keyguard happened to be installed.
            env = os.environ.get(EMAIL_ENV, "").strip()
            if env:
                return env
            try:
                import json
                data = json.loads(cls.config_path().read_text(encoding="utf-8"))
            except (OSError, ValueError):
                return ""
            return str(data.get("email", "")).strip()

        @classmethod
        def set_licensee_email(cls, email: str) -> None:
            # Persist to disk like AppGate does. Setting os.environ only looked
            # like it worked and was gone at process exit, so `--licence-email`
            # silently did nothing.
            import json
            path = cls.config_path()
            path.parent.mkdir(parents=True, exist_ok=True)
            payload: dict = {}
            try:
                payload = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, ValueError):
                pass
            payload["email"] = email.strip()
            path.write_text(json.dumps(payload, indent=2, ensure_ascii=False),
                            encoding="utf-8")

        @classmethod
        def check(cls) -> LicenceState:
            return LicenceState(
                True,
                "unknown",
                "keyguard not installed",
                enforced=cls.should_enforce(),
                email=cls.licensee_email(),
            )

        @staticmethod
        def activate(key: str, email: str = "") -> tuple[bool, str]:
            return False, "keyguard is not installed in this build"

        @staticmethod
        def report_cli(ok: bool, message: str, *, title: str = "") -> int:
            print(f"{'OK' if ok else 'FAILED'}: {message}")
            return 0 if ok else 1

        @staticmethod
        def refuse_in_window(state, **kwargs) -> bool:
            return False

        @staticmethod
        def refresh_licence(**kwargs) -> str:
            return ""

        @classmethod
        def licence_inboxes(cls) -> list:
            return [cls.state_dir() / "licences"]

        @classmethod
        def status_cache_path(cls) -> Path:
            return cls.state_dir() / "licence-status.json"

        @staticmethod
        def revocation() -> Optional[dict]:
            return None

        @staticmethod
        def exit_with_message(state, code: int = 2) -> None:
            raise SystemExit(code)

        @staticmethod
        def machine_id() -> str:
            return ""

        @classmethod
        def enforce_or_exit(cls) -> LicenceState:
            return cls.check()

    GATE = _MissingGate()
else:
    GATE = AppGate(
        APP_ID,
        app_name=APP_NAME,
        enforce_env=ENFORCE_ENV,
        email_env=EMAIL_ENV,
    )

# Stable application-facing surface.
check = GATE.check
activate = GATE.activate
machine_id = GATE.machine_id
licensee_email = GATE.licensee_email
set_licensee_email = GATE.set_licensee_email
should_enforce = GATE.should_enforce
enforce_or_exit = GATE.enforce_or_exit
# Reports one-shot commands where they can actually be seen. This build is
# GUI-subsystem, so `print()` resolves file=None to a None sys.stdout and
# returns silently -- a failed --activate looked exactly like a successful one.
report_cli = GATE.report_cli
# Refuse inside a window that looks like this application rather than a bare
# dialog with nothing behind it -- the latter reads as a launcher that broke.
refuse_in_window = GATE.refuse_in_window
# Looks for a licence the vendor has already renewed, so a customer whose
# renewal is sitting in their inbox folder is not refused for a licence that
# exists. Can only ever extend -- see AppGate.refresh_licence.
#: Where this build looks for the supplier's current word on a licence.
#: Baked in rather than configured on the customer's machine -- a URL somebody
#: can point elsewhere is a URL that can be pointed at nothing. The environment
#: variable stays for testing and for customers behind a mirror.
#: A release asset, not a branch path. Two reasons, both operational:
#:
#: Publishing a withdrawal used to mean pushing to `master`, so every
#: revocation needed a pull request -- branch protection exists to guard code
#: review, and having it stand between a vendor and cutting off access was an
#: accident of where the files happened to live. `gh release upload --clobber`
#: touches no branch.
#:
#: And raw.githubusercontent serves `Cache-Control: max-age=300`, so a
#: withdrawal took minutes to propagate. Release downloads are `no-cache`.
STATUS_URL = os.environ.get(
    "FAKE_TRIAL_POKE_LICENCE_URL",
    "https://github.com/gsinvest017-ai/fake-trial-poke/releases/download"
    "/licence-status/{app}-{email_sha256}.txt",
).strip()

refresh_licence = GATE.refresh_licence
licence_inboxes = GATE.licence_inboxes
#: Where the last status statement this client believed is cached, and what it
#: currently says. Exposed so `--licence-refresh` can show *which* statement is
#: in force: during a revocation test the only way to tell "the new statement
#: arrived" from "I am still looking at the cached one" is statement_utc, and a
#: statement is only accepted when that value increases.
status_cache_path = GATE.status_cache_path
revocation = GATE.revocation
exit_with_message = GATE.exit_with_message
check_state = GATE.check

try:
    from keyguard.appgate import attach_parent_console
except Exception:                                             # noqa: BLE001
    def attach_parent_console() -> bool:                      # type: ignore[misc]
        """Fallback for a build without keyguard: report whatever stdout is."""
        import sys as _sys
        return getattr(_sys, "stdout", None) is not None

# Compatibility helpers used by existing integrations and their tests.
_user_data_dir = GATE.state_dir
_config_path = GATE.config_path
_console_safe = console_safe
